In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

# SETTING 1

In [2]:
X = []
Y = []
beta = [2, 1, 0, 0]
for i in range(5):
    rdnorm_4d = np.random.randn(1, 4)
    X.append(rdnorm_4d)
    
    Y.append(np.dot(rdnorm_4d, beta) + np.random.randn(1))
    

In [3]:
X

[array([[-0.52917821, -0.34327668, -0.0707058 ,  0.29983096]]),
 array([[-0.05343042, -0.52423847, -0.31718531, -0.73352361]]),
 array([[ 0.97629413, -0.82191998,  1.44064248,  1.09801481]]),
 array([[ 0.32117632, -0.57403546,  0.29700136, -0.47120334]]),
 array([[-0.50766793,  1.56112719, -1.15920199,  0.11542984]])]

In [4]:
Y

[array([-2.0796582]),
 array([-0.53906381]),
 array([2.41798146]),
 array([1.23000986]),
 array([1.44092702])]